env:
  browser: true
  es2021: true
extends: standard-with-typescript
overrides:
  [{ files: ["*.ts"], parserOptions: { project: ["./tsconfig.json"] } }]
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  {
    "@typescript-eslint/space-before-function-paren": "warn",
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/comma-dangle": "warn",
    "@typescript-eslint/prefer-nullish-coalescing": "warn",
    "@typescript-eslint/no-unused-vars": "warn",
  }
