env:
  browser: true
  es2021: true
extends: standard-with-typescript
overrides:
  [{ files: ["*.ts"], parserOptions: { project: ["./tsconfig.json"] } }]
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  {
    "space-before-function-paren": "off",
    "@typescript-eslint/space-before-function-paren": "off",
  }
