version: '3.7'
services:
  axiebot:
    build: .
    user: node
    env_file: .env
    volumes:
      - .:/workspace:cached
    ports:
      - target: 3000
        published: 8081
        protocol: tcp
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:alpine
    # ports:
    #   - target: 5432
    #     published: 5432
    #     protocol: tcp
    environment:
      POSTGRES_USER: ${POSTGRES_USER-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-password}
      POSTGRES_DB: ${POSTGRES_DB-axiebot}
    volumes:
      - ./data-postgres:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD-password}"
    volumes:
      - ./data-redis:/data
  admin:
    image: adminer
    depends_on: 
      - postgres
    ports:
      - 8080:8080

