version: '3.7'
services:
  axiebot:
    build: .
    restart: unless-stopped
    user: node
    env_file: .env
    volumes:
      - .:/workspace:cached
    command: ["npm", "run", "${NODE_DEV-start}"]
    ports:
      - target: 3001
        published: ${EXPRESS_PORT-3001}
        protocol: tcp