version: '3.7'
services:
  axiebot:
    build: .
    user: node
    env_file: .env
    volumes:
      - .:/workspace:cached
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:alpine
    env_file: .env
    ports:
      - target: 5432
        published: 5434
        protocol: tcp
    volumes:
      - ./data-postgres:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD-password}"
    volumes:
      - ./data-redis:/data
  admin:
    image: adminer
    depends_on:
      - postgres
    ports:
      - 8081:8080
