version: '3.7'
services:
  axiebot:
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    volumes:
      - .:/workspace:cached
      # Uncomment the next line to use Docker from inside the container. See https://aka.ms/vscode-remote/samples/docker-from-docker-compose for details.
      # - /var/run/docker.sock:/var/run/docker.sock 